/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarisign.vista;

import clarisign.DB.*;
import clarisign.modelo.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Connection;
import java.util.List;

public class DashboardPacienteView extends JFrame {

    private JTable tablaSesiones;
    private int idPaciente;

    public DashboardPacienteView(int idPaciente) {
        this.idPaciente = idPaciente;
        setTitle("Panel del Paciente");
        setSize(800, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Tabla de sesiones
        tablaSesiones = new JTable();
        JScrollPane scrollPane = new JScrollPane(tablaSesiones);

        // Botones
        JButton btnSolicitarSesion = new JButton("Solicitar Sesión");
        btnSolicitarSesion.addActionListener(e -> { new SolicitudSesionPacienteView(idPaciente, this);
        cargarSesiones();});
        
        JButton btnIngresarSesion = new JButton("Ingresar a la Sesión");
        btnIngresarSesion.addActionListener(e -> { ingresarSesion();
        cargarSesiones();});
        
        JButton btnCerrarSesion = new JButton("Cerrar Sesión");
        btnCerrarSesion.addActionListener(e -> {
            dispose(); // Cierra el panel actual
            new LoginView().setVisible(true);
                    cargarSesiones();
        });

        JPanel panelBotones = new JPanel();
        panelBotones.add(btnSolicitarSesion);
        panelBotones.add(btnIngresarSesion);
        panelBotones.add(btnCerrarSesion);

        add(new JLabel("Sesiones Programadas", SwingConstants.CENTER), BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(panelBotones, BorderLayout.SOUTH);

        cargarSesiones();
        setVisible(true);
    }

    public void cargarSesiones() {
        try (Connection conn = DBConnection.getConnection()) {
            SesionDAO dao = new SesionDAO(conn);
            InterpreteDAO interpreteDAO = new InterpreteDAO(conn);
            TerapeutaDAO terapeutaDAO = new TerapeutaDAO(conn);
            
            List<Sesion> sesiones = dao.listarSesionesPorPaciente(idPaciente);
            
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"ID", "Terapeuta", "Intérprete", "Fecha", "Estado"});

            for (Sesion s : sesiones) {
            Interprete interprete = s.getIdInterprete() != null ? interpreteDAO.obtenerPorId(s.getIdInterprete()) : null;
            Terapeuta terapeuta = terapeutaDAO.obtenerPorId(s.getIdTerapeuta());

            // Si no hay intérprete, asignamos "Desconocido"
            String nombreInterprete = (interprete != null) ? interprete.getNombre() : "Desconocido";
            // Si no hay terapeuta, asignamos "Desconocido"
            String nombreTerapeuta = (terapeuta != null) ? terapeuta.getNombre() : "Desconocido";
            
            // Agregamos la fila a la tabla
            model.addRow(new Object[]{
                s.getId(),
                nombreTerapeuta,
                nombreInterprete,
                s.getFechaHora(),
                s.getEstado()
            });
        }

        tablaSesiones.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar sesiones: " + e.getMessage());
        }
    }
    
    private void ingresarSesion() {
        int fila = tablaSesiones.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una sesión.");
            return;
        }

        String estado = tablaSesiones.getValueAt(fila, 4).toString();
        if (!"en curso".equalsIgnoreCase(estado)) {
            JOptionPane.showMessageDialog(this, "Solo puedes ingresar a sesiones 'en curso'.");
            return;
        }
        

        int idSesion = (int) tablaSesiones.getValueAt(fila, 0);
        // Aquí podrías abrir una nueva vista que simule el desarrollo de la sesión
        JOptionPane.showMessageDialog(this, "Ingresando a la sesión ID: " + idSesion);
        new VideoLlamadaSimuladaView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
