/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarisign.vista;

import clarisign.controlador.RegistroController;
import clarisign.modelo.Paciente;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author MARCE
 */
public class RegistroView extends JFrame {

    private JTextField txtNombre;
    private JTextField txtCorreo;
    private JPasswordField txtContrasena;
    private JTextField txtDiagnostico;
    private JButton btnRegistrar;
    
    private DashboardPacienteView dashboard;
    
    public RegistroView() {
        this.dashboard = dashboard;
        
        setTitle("Registro de Paciente");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new GridLayout(5, 2, 5, 5));

        txtNombre = new JTextField();
        txtCorreo = new JTextField();
        txtContrasena = new JPasswordField();
        txtDiagnostico = new JTextField();
        btnRegistrar = new JButton("Registrar");

        add(new JLabel("Nombre:")); add(txtNombre);
        add(new JLabel("Correo:")); add(txtCorreo);
        add(new JLabel("Contraseña:")); add(txtContrasena);
        add(new JLabel("Diagnóstico:")); add(txtDiagnostico);
        add(new JLabel()); add(btnRegistrar);

        btnRegistrar.addActionListener(e -> registrarPaciente());
        aplicarEstilos();
        setVisible(true);
    }

    private void registrarPaciente() {
        String nombre = txtNombre.getText().trim();
        String correo = txtCorreo.getText().trim();
        String contrasena = new String(txtContrasena.getPassword()).trim();
        String diagnostico = txtDiagnostico.getText().trim();

        if (nombre.isEmpty() || correo.isEmpty() || contrasena.isEmpty() || diagnostico.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
        }

        Paciente paciente = new Paciente(0, nombre, correo, contrasena, diagnostico);

        RegistroController controller = new RegistroController();
        if (controller.registrarPaciente(paciente)) {
            JOptionPane.showMessageDialog(this, "Registro exitoso.");
            if (dashboard != null) {
                dashboard.cargarSesiones(); // ✅ Actualiza el dashboard
            }            
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el paciente.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarEstilos() {
        Color blanco = Color.WHITE;
    Color grisClaro = new Color(245, 245, 245);
    Color moradoPastel = new Color(180, 140, 200);
    Color textoMorado = new Color(100, 60, 130);

    Font fuenteLabel = new Font("SansSerif", Font.BOLD, 13);
    Font fuenteCampo = new Font("SansSerif", Font.PLAIN, 13);
    Font fuenteBoton = new Font("SansSerif", Font.BOLD, 14);

    getContentPane().setBackground(grisClaro);

    for (Component c : getContentPane().getComponents()) {
        if (c instanceof JLabel label) {
            label.setFont(fuenteLabel);
            label.setForeground(textoMorado);
        } else if (c instanceof JTextField || c instanceof JPasswordField) {
            c.setFont(fuenteCampo);
        } else if (c instanceof JButton btn) {
            btn.setFont(fuenteBoton);
            btn.setBackground(moradoPastel);
            btn.setForeground(blanco);
            btn.setFocusPainted(false);
            btn.setBorder(BorderFactory.createEmptyBorder(8, 16, 8, 16));
        }
    }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
