/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarisign.vista;

import clarisign.DB.DBConnection;
import clarisign.DB.TerapeutaDAO;
import clarisign.controlador.SolicitudSesionController;
import clarisign.modelo.Terapeuta;
import clarisign.modelo.Sesion;
import clarisign.modelo.Paciente;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.util.List;

public class SolicitudSesionPacienteView extends javax.swing.JFrame {
    
    private JComboBox<Terapeuta> cbTerapeutas;
    private JButton btnSolicitar;
    private DashboardPacienteView dashboard;
    
    private int idPaciente;
    /**
     * Creates new form SolicitudSesionPacienteView
     */
    public SolicitudSesionPacienteView(int idPaciente, DashboardPacienteView dashboard) {
        this.dashboard=dashboard;
        this.idPaciente = idPaciente;
        
        setTitle("Solicitar Sesión");
        setSize(400, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new GridLayout(3, 2, 5, 5));

        cbTerapeutas = new JComboBox<>();
        btnSolicitar = new JButton("Enviar Solicitud");

        add(new JLabel("Selecciona un terapeuta:"));
        add(cbTerapeutas);
        add(new JLabel()); // espacio vacío
        add(btnSolicitar);

        btnSolicitar.addActionListener(e -> enviarSolicitud());

        cargarTerapeutas();
        aplicarEstilos();
        setVisible(true);
    }

    private void cargarTerapeutas() {
        try (Connection conn = DBConnection.getConnection()) {
            List<Terapeuta> terapeutas = new TerapeutaDAO(conn).listarTodos();
            for (Terapeuta t : terapeutas) cbTerapeutas.addItem(t);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar terapeutas: " + e.getMessage());
        }
    }

    private void enviarSolicitud() {
        try {
            Terapeuta terapeuta = (Terapeuta) cbTerapeutas.getSelectedItem();
            if (terapeuta == null) {
                JOptionPane.showMessageDialog(this, "Selecciona un terapeuta.");
                return;
            }

    Sesion sesion = new Sesion(
        0,
           idPaciente,
  terapeuta.getId(),
 null,
    null,
     "solicitando"
);

            SolicitudSesionController controller = new SolicitudSesionController();
            if (controller.enviarSolicitud(sesion)) {
                JOptionPane.showMessageDialog(this, "Solicitud enviada al terapeuta.");
                if (dashboard != null) {
                dashboard.cargarSesiones(); // ✅ Refresca la tabla
            }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al enviar la solicitud.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarEstilos() {
    Color blanco = Color.WHITE;
    Color grisClaro = new Color(245, 245, 245);
    Color moradoPastel = new Color(180, 140, 200);
    Color textoMorado = new Color(100, 60, 130);

    Font fuenteLabel = new Font("SansSerif", Font.BOLD, 13);
    Font fuenteCombo = new Font("SansSerif", Font.PLAIN, 13);
    Font fuenteBoton = new Font("SansSerif", Font.BOLD, 14);

    getContentPane().setBackground(grisClaro);

    for (Component c : getContentPane().getComponents()) {
        if (c instanceof JLabel label) {
            label.setFont(fuenteLabel);
            label.setForeground(textoMorado);
        } else if (c instanceof JComboBox<?> combo) {
            combo.setFont(fuenteCombo);
        } else if (c instanceof JButton btn) {
            btn.setFont(fuenteBoton);
            btn.setBackground(moradoPastel);
            btn.setForeground(blanco);
            btn.setFocusPainted(false);
            btn.setBorder(BorderFactory.createEmptyBorder(8, 16, 8, 16));
        }
    }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
